### ISSUE TITLE
Class 'NewRelic\NewRelic' not found

### ISSUE THREAD

**Issue by AntoineTurmel** [bazilio91/yii2-newrelic#4]
I am manually installing the extension and I have:
PHP Fatal Error – yii\base\ErrorException
Class 'NewRelic\NewRelic' not found

all folders are in vendor, and I added "bazilio/yii2-newrelic" inside "/vendor/yiisoft/extensions.php"

should I add "sobanvuex/php-newrelic" somewhere ?

**Comment by bazilio91** [comment]
Never tried to install ext manualy, but yes, `NewRelic\NewRelic` from "sobanvuex/php-newrelic" should be available to get it right.

**Comment by bazilio91** [comment]
Closed due inactivity
